#!/bin/bash

DST=$1
VM_ID=$2
DS_ID=$3

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

source $TMCOMMON

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../../datastore/drbdmanage/drbd_common.sh

drbd_log "Begining delete action."

# Get virtualization host information
DST_PATH=$(arg_path $DST)
SRC_PATH=$(arg_path $SRC)
DST_HOST=$(arg_host $DST)
DST_DIR=$(dirname $DST_PATH)
DISK_ID=$(echo "$DST_PATH" | $AWK -F. '{print $NF}')

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j

while IFS= read -r -d '' element; do
      XPATH_ELEMENTS[i++]="$element"
    done < <(onevm show -x $VM_ID| $XPATH \
                        /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE \
                        /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/PERSISTENT)

    DRBD_RES_NAME="${XPATH_ELEMENTS[j++]}"
    PERSISTENT="${XPATH_ELEMENTS[j++]}"

# Link DRBD device to datastore location.
UNLINK_COMMAND=$(cat <<EOF
    set -e

    rm -f "$DST_PATH"
EOF
)

ssh_exec_and_log "$DST_HOST" "$UNLINK_COMMAND" \
          "Error: Unable to remove symbolic link $DST_PATH on $DST_HOST"

if [ -n $PERSISTENT ]; then
  drbd_remove_res $DRBD_RES_NAME-vm${VM_ID}-disk${DISK_ID}

  drbd_log "Ending non-persistent delete action."

  exit 0
else
  drbd_log "Ending persistent delete action."

  exit 0
fi
