#!/bin/bash
#
#==========================================================================
# Copyright 2016 LINBIT USA LCC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#==========================================================================

SRC=$1
DST=$2

VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON="${ONE_LOCATION}"/var/remotes/tm/tm_common.sh
fi

source "$TMCOMMON"

DRIVER_PATH=$(dirname "$0")
source "${DRIVER_PATH}"/../../datastore/drbdmanage/drbdmanage.conf
source "${DRIVER_PATH}"/../../datastore/drbdmanage/drbd_common.sh

drbd_log "Beginning ln action."

# Get host information
DST_PATH=$(arg_path "$DST")
SRC_PATH=$(arg_path "$SRC")
DST_HOST=$(arg_host "$DST")
DST_DIR=$(dirname "$DST_PATH")

# Get resource name and assign it to the host.
DRBD_RES_NAME=$SRC_PATH
drbd_deploy_res_on_host "$DRBD_RES_NAME" "$DST_HOST"

# Get Device path and make sure it's ready for IO.
DRBD_DEVICE_PATH=$(drbd_get_device_for_res "$DRBD_RES_NAME")

exec_and_log "drbd_is_node_ready $DST_HOST $DRBD_DEVICE_PATH" \
  "DRBD device at $DRBD_DEVICE_PATH not ready for IO on $DST_HOST"

# Link DRBD device to datastore location.
LINK_COMMAND=$(cat <<EOF
    set -e

    mkdir -p $DST_DIR

    ln -fs "$DRBD_DEVICE_PATH" "$DST_PATH"
EOF
)

ssh_exec_and_log "$DST_HOST" "$LINK_COMMAND" \
          "Error: Unable to link $DRBD_RES_NAME to $DST_PATH on $DST_HOST"

drbd_log "Ending ln action."

exit 0
