#!/bin/bash

SRC=$1
DST=$2

VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

source $TMCOMMON

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../../datastore/drbdmanage/drbd_common.sh

drbd_log "Begining mv action."
# Get virtualization host information
DST_PATH=$(arg_path $DST)
SRC_PATH=$(arg_path $SRC)
DST_HOST=$(arg_host $DST)
DST_DIR=$(dirname $DST_PATH)

drbd_log "src: $SRC"
drbd_log "dst: $DST"
drbd_log "vm id: $VM_ID"
drbd_log "ds is: $DS_ID"


drbd_log "dst_path: $DST_PATH"
drbd_log "src path: $SRC_PATH"
drbd_log "dst host: $DST_HOST"
drbd_log "dst dir: $DST_DIR"

drbd_log "Ending mv action."

exit 0
