#!/bin/bash

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON="${ONE_LOCATION}"/var/remotes/tm/tm_common.sh
fi

source "$TMCOMMON"

DRIVER_PATH=$(dirname "$0")
source "${DRIVER_PATH}"/../../datastore/drbdmanage/drbd_common.sh
source "${DRIVER_PATH}"/../../datastore/drbdmanage/drbdmanage.conf

drbd_log "Begining mvds action."

# Get virtualization host information
SRC_PATH=$(arg_path "$SRC")
SRC_HOST=$(arg_host "$SRC")
DISK_ID=$(echo "$SRC" | $AWK -F. '{print $NF}')

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
  XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x "$VM_ID" | $XPATH \
  /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE \
  /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SAVE_AS \
  /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/PERSISTENT)

DRBD_RES_NAME="${XPATH_ELEMENTS[j++]}"
SAVE_AS="${XPATH_ELEMENTS[j++]}"
PERSISTENT="${XPATH_ELEMENTS[j++]}"

# Link DRBD device to datastore location.
UNLINK_COMMAND=$(cat <<EOF
    set -e

    rm -f "$SRC_PATH"
EOF
)

ssh_exec_and_log "$SRC_HOST" "$UNLINK_COMMAND" \
          "Error: Unable to remove symbolic link $SRC_PATH on $SRC_HOST"

# If the image is not persisent
if [ -z $"PERSISTENT" ]; then
  drbd_unassign_res "${DRBD_RES_NAME}-vm${VM_ID}-disk${DISK_ID}"

  drbd_log "Ending non-persistent mvds action."

  exit 0
else
  drbd_log "Unassigning $DRBD_RES_NAME from $SRC_HOST"

  drbd_unassign_res "$DRBD_RES_NAME" "$SRC_HOST"

  drbd_log "Ending persistent mvds action."

  exit 0
fi
