#!/bin/bash

SRC=$1
SNAP_ID=$2
VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON="${ONE_LOCATION}"/var/remotes/tm/tm_common.sh
fi

source "$TMCOMMON"

DRIVER_PATH=$(dirname "$0")
source "${DRIVER_PATH}"/../../datastore/drbdmanage/drbd_common.sh
source "${DRIVER_PATH}"/../../datastore/drbdmanage/drbdmanage.conf

drbd_log "Beginning snap_create action."

drbd_log "src: $SRC"
drbd_log "snap_id: $SNAP_ID"
drbd_log "VM_ID: $VM_ID"
drbd_log "DS_ID: $DS_ID"

drbd_log "Ending snap_create action."

exit 0
