#!/bin/bash

addon_path=$(dirname "$0")
driver_path=$(dirname "$addon_path")
driver_name=$(basename "$driver_path")

script_name="${0##*/}"

source "${addon_path}"/../../scripts_common.sh

error_message "$driver_name-$script_name: Operation not supported"

exit 1
