#!/bin/bash
#
#==========================================================================
# Copyright 2016 LINBIT USA LCC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#==========================================================================

# Set up environment
if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

source "${LIB_LOCATION}"/sh/scripts_common.sh

DRIVER_PATH=$(dirname "$0")
source "${DRIVER_PATH}"/../libfs.sh
source "${DRIVER_PATH}"/drbdmanage.conf
source "${DRIVER_PATH}"/drbd_common.sh

drbd_log "Beginning clone action."

# Get arguments from OpenNebula Core
DRIVER_ACTION=$1
IMAGE_ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRIVER_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_MIN_RATIO \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_MIN_COUNT \
                    /DS_DRIVER_ACTION_DATA/IMAGE/PATH)

BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"
DRBD_MIN_RATIO="${XPATH_ELEMENTS[j++]:-$DRBD_MIN_RATIO}"
DRBD_MIN_COUNT="${XPATH_ELEMENTS[j++]:-$DRBD_MIN_COUNT}"
DRBD_RES_NAME="${XPATH_ELEMENTS[j++]}"

DST_HOST=$(get_destination_host "$IMAGE_ID")

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

DRBD_CLONE_NAME=OpenNebula-clone-${IMAGE_ID}

# Make a new resource from an existing one.
if [ "$(drbd_clone_res "$DRBD_CLONE_NAME" "$DRBD_RES_NAME")" -ne 0 ]; then
  error_message "Unable to deploy $DRBD_CLONE_NAME"

  # Clean up resource.
  drbd_remove_res "$DRBD_CLONE_NAME"
  exit -1
fi

# Distribute resource to remaning nodes if live migration is enabled.
if [ "$DRBD_SUPPORT_LIVE_MIGRATION" = "yes" ];then
  drbd_distribute_clients "$DRBD_CLONE_NAME"
fi

echo "$DRBD_CLONE_NAME"

drbd_log "Ending clone action."

exit 0
