#!/bin/bash
#
#==========================================================================
# Copyright 2016 LINBIT USA LCC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#==========================================================================

# Set up environment
if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

source "$LIB_LOCATION"/sh/scripts_common.sh

DRIVER_PATH=$(dirname "$0")
source "${DRIVER_PATH}"/../libfs.sh
source "${DRIVER_PATH}"/drbdmanage.conf
source "${DRIVER_PATH}"/drbd_common.sh

drbd_log "Beginning mkfs action."

# Get arguments from OpenNebula Core
DRIVER_ACTION=$1
IMAGE_ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRIVER_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/RESTRICTED_DIRS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SAFE_DIRS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_REDUNDANCY \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_DEPLOYMENT_NODES \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_MIN_RATIO \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_MIN_COUNT \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_SUPPORT_LIVE_MIGRATION \
                    /DS_DRIVER_ACTION_DATA/IMAGE/FSTYPE \
                    /DS_DRIVER_ACTION_DATA/IMAGE/SIZE)

BASE_PATH="${XPATH_ELEMENTS[j++]}"
RESTRICTED_DIRS="${XPATH_ELEMENTS[j++]}"
SAFE_DIRS="${XPATH_ELEMENTS[j++]}"
BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"
DRBD_REDUNDANCY="${XPATH_ELEMENTS[j++]}"
DRBD_DEPLOYMENT_NODES="${XPATH_ELEMENTS[j++]}"
DRBD_MIN_RATIO="${XPATH_ELEMENTS[j++]:-$DRBD_MIN_RATIO}"
DRBD_MIN_COUNT="${XPATH_ELEMENTS[j++]:-$DRBD_MIN_COUNT}"
DRBD_SUPPORT_LIVE_MIGRATION="${XPATH_ELEMENTS[j++]:-$DRBD_SUPPORT_LIVE_MIGRATION}"
FSTYPE="${XPATH_ELEMENTS[j++]}"
SIZE="${XPATH_ELEMENTS[j++]:-0}"

DST_HOST=$(get_destination_host "$IMAGE_ID")

# Check for valid configuration.
exec_and_log "drbd_deploy_options_check" \
  "You must have only one of the following in the template \
  for your datastore: DRBD_REDUNDANCY DRBD_DEPLOYMENT_NODES"

# Get the name and size for a DRBD resource.
DRBD_SIZE="${SIZE}M"
DRBD_RES_NAME="OpenNebula-image-${IMAGE_ID}"

# Check size of the new resource for redundant deployments.
if [ -n "$DRBD_REDUNDANCY" ]; then
  exec_and_log "drbd_size_check $SIZE" \
    "Unable to find $DRBD_REDUNDANCY storage nodes with enough \
    free space to hold a new $DRBD_SIZE volume."
fi

# Do not make a new resource for save as, just return the name.
if [  "$FSTYPE" = "save_as" ]; then
    drbd_log "No need to create new image, exiting."

    echo "$DRBD_RES_NAME"
    exit 0
fi

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS"

# Create new resource in DRBD.
drbd_log "Creating a new $DRBD_SIZE resource $DRBD_RES_NAME" 

drbd_add_res "$DRBD_RES_NAME" "$DRBD_SIZE"
if [ "$(drbd_deploy_res_on_nodes "$DRBD_RES_NAME")" -ne 0 ]; then
  error_message "Unable to deploy $DRBD_RES_NAME"

  # Clean up resource.
  drbd_remove_res "$DRBD_RES_NAME"
  exit -1
fi

# Get the location of the DRBD device node.
DRBD_DEVICE_PATH=$(drbd_get_device_for_res "$DRBD_RES_NAME")

# Create filesystem on DRBD device.
REGISTER_COMMAND=$(cat << EOF
  set -e

  export PATH=/usr/sbin:/sbin:\$PATH

  if [ -z "$FSTYPE" ] || [ "$FSTYPE" == "raw" ]; then
    exit 0
  fi

  $SUDO $(mkfs_command "$DRBD_DEVICE_PATH" "$FSTYPE" "$SIZE")

EOF
)

# Find node with a resource assigned to it.
RES_NODES=$(drbd_get_res_nodes "$DRBD_RES_NAME")
RES_HOST=$(drbd_get_assignment_node "$DRBD_DEVICE_PATH" $RES_NODES)

if [ -z "$RES_HOST" ]; then
  error_message "No node in $RES_NODES ready for IO on $DRBD_DEVICE_PATH"

  # Clean up resource.
  drbd_remove_res "$DRBD_RES_NAME"
  exit -1
fi

# Create a filesytem on a resource.
$(ssh_exec_and_log "$RES_HOST" "$REGISTER_COMMAND" \
  "Error registering $DRBD_RES_NAME on $RES_HOST")


# Clean up resources on failure.
REGISTER_RC=$?

if [ "$REGISTER_RC" -ne 0 ]; then
  drbd_remove_res "$DRBD_RES_NAME"
  exit -1
fi

# Distribute resource to remaning nodes if live migration is enabled.
if [ "$DRBD_SUPPORT_LIVE_MIGRATION" = "yes" ];then
  drbd_distribute_clients "$DRBD_RES_NAME"
fi

drbd_log "Created $DRBD_RES_NAME on $RES_HOST"
drbd_log "Ending mkfs action."

echo "$DRBD_RES_NAME"
