#!/bin/bash
#
#==========================================================================
# Copyright 2016 LINBIT USA LCC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#==========================================================================

# Set up environment
if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

source "$LIB_LOCATION"/sh/scripts_common.sh

DRIVER_PATH=$(dirname "$0")
source "${DRIVER_PATH}"/../libfs.sh
source "${DRIVER_PATH}"/drbdmanage.conf
source "${DRIVER_PATH}"/drbd_common.sh

# Get arguments from OpenNebula Core
DRIVER_ACTION=$1
IMAGE_ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRIVER_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_REDUNDANCY \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_DEPLOYMENT_SITE \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DRBD_DEPLOYMENT_NODES )

DRBD_REDUNDANCY="${XPATH_ELEMENTS[j++]}"
DRBD_DEPLOYMENT_SITE="${XPATH_ELEMENTS[j++]}"
DRBD_DEPLOYMENT_NODES="${XPATH_ELEMENTS[j++]}"

DST_HOST=$(get_destination_host "$IMAGE_ID")

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

# Monitor pool space.
if [ -n "$DRBD_DEPLOYMENT_NODES" ]; then
  # Use the smallest pool sizes among the deployment nodes.
  TOTAL_MB=$(sudo drbdmanage n -N $DRBD_DEPLOYMENT_NODES -m | \
    awk -F',' '{ if (!total || $4<total) total=$4 } END { print total / 1024 }')
  FREE_MB=$(sudo drbdmanage n -N $DRBD_DEPLOYMENT_NODES -m | \
    awk -F',' '{ if (!total || $5<total) total=$5 } END { print total / 1024 }')
else
  # Calculate how much space is left for redundant volumes.
  TOTAL_MB=$(sudo drbdmanage free-space "$DRBD_REDUNDANCY" --site "$DRBD_DEPLOYMENT_SITE" -m | \
    awk -F',' -v redundancy="$DRBD_REDUNDANCY" '{print $2 / 1024 / redundancy}')
  FREE_MB=$(sudo drbdmanage n -N $(drbd_get_site_nodes "$DRBD_DEPLOYMENT_SITE") -m | \
    awk -F',' -v redundancy="$DRBD_REDUNDANCY" 'BEGIN { total=$5 } { total += $5 } END { print total / 1024 / redundancy }')
fi

USED_MB=$((TOTAL_MB - FREE_MB))

echo "FREE_MB=$FREE_MB"
echo "USED_MB=$USED_MB"
echo "TOTAL_MB=$TOTAL_MB"
