#!/bin/bash

# Set up environment

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/drbd_common.sh

# Get arguments from OpenNebula Core

DRIVER_ACTION=$1
IMAGE_ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRIVER_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST )

BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"

DST_HOST=`get_destination_host $IMAGE_ID`

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

drbd_monitor $BRIDGE_LIST
drbd_monitor () {
  nodes="${@:1}"

  USED_MB=$(sudo drbdmanage v -m | awk -F',' '{ sum+=$4 } END { print sum / 1024 }')
  TOTAL_MB=$(sudo drbdmanage n -N $nodes -m | \
    awk -F',' '{ if (!total || $4<total) total=$4 } END { print total / 1024 }')
  FREE_MB=$(($TOTAL_MB - $USED_MB))

  echo "FREE_MB=$FREE_MB"
  echo "USED_MB=$USED_MB"
  echo "TOTAL_MB=$TOTAL_MB"
}
