#!/bin/bash

# Set up environment

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/drbd_common.sh
source ${DRIVER_PATH}/drbd.conf

drbd_log "Begining rm action."

# Get arguments from OpenNebula Core

DRIVER_ACTION=$1
IMAGE_ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRIVER_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH /DS_DRIVER_ACTION_DATA/IMAGE/SOURCE)

DRBD_RES_NAME="${XPATH_ELEMENTS[0]}"

# Check if resource is there before it's removed.
if [ -z "$(drbd_res_exsists $DRBD_RES_NAME)" ]; then
  drbd_log "No resource nammed $DRBD_RES_NAME: cannot remove."
  exit -1
fi

drbd_remove_res $DRBD_RES_NAME

drbd_log "Ending rm action."

exit 0
